/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import dados.IDAOApostador;
import java.util.ArrayList;
import javax.swing.JOptionPane;

import modelo.*;
import dados.*;
import controle.*;
import javax.swing.JOptionPane;
import modelo.ObjetoAposta;

/**
 *
 * @author guest-sAzh4k
 */
public class TelaResultado extends javax.swing.JFrame {

    private Principal telaAnterior;
    private boolean selecionou = false;
    private IGerenciadorApostador gerenciadorApostador;
    
    /**
     * Creates new form NovoApostador
     */
    public TelaResultado() {
        initComponents();
    }
    
    public TelaResultado(Principal principal, IGerenciadorApostador gerA) {
        telaAnterior = principal;
        initComponents();
        gerenciadorApostador = gerA;
      
        cbObjetos.removeAllItems();       
        IO io = new EntradaSaidaCavalos();        
           
        for (int i = 0; i < io.getObjetosAposta().size(); i++){
           cbObjetos.addItem(io.getObjetosAposta().get(i).getNome());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoGanhador = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        cbObjetos = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cbObjetos2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GA - Resultado");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Resultado:");

        jButton2.setText("Sair");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        textoGanhador.setColumns(20);
        textoGanhador.setRows(5);
        jScrollPane1.setViewportView(textoGanhador);

        jLabel2.setText("Insira o primeiro objeto ganhador: ");

        cbObjetos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbObjetos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbObjetosActionPerformed(evt);
            }
        });

        jLabel3.setText("Insira o segundo objeto ganhador: ");

        cbObjetos2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbObjetos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbObjetos2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel1))
                            .addGap(50, 50, 50)
                            .addComponent(cbObjetos2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(53, 53, 53)
                            .addComponent(cbObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cbObjetos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jButton2)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        telaAnterior.setEnabled(true);
        this.dispose();              
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Ao fechar a janela;
        telaAnterior.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void cbObjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbObjetosActionPerformed
        // usuario selecionou o objeto ganhador
        
         cbObjetos2.removeAllItems();
         textoGanhador.removeAll();
            
        IO io = new EntradaSaidaCavalos();                                
           
        for (int i = 0; i < io.getObjetosAposta().size(); i++){
            if(io.getObjetosAposta().get(i).getNome() == cbObjetos.getSelectedItem()){    
            }
            else
            {
                cbObjetos2.addItem(io.getObjetosAposta().get(i).getNome());
            }
        }
    }//GEN-LAST:event_cbObjetosActionPerformed

    private void cbObjetos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbObjetos2ActionPerformed
        textoGanhador.removeAll();
        
        IO io = new EntradaSaidaCavalos(); 
        int id = cbObjetos.getSelectedIndex();
        String item1 = String.valueOf(cbObjetos.getSelectedItem());
        String item2 = String.valueOf(cbObjetos2.getSelectedItem());  
        
        try {
        if(id > -1){
            ArrayList<ObjetoAposta> objetosGanhadores = new ArrayList<ObjetoAposta>();
            ObjetoAposta obj = new ObjetoAposta(item1);
            objetosGanhadores.add(obj);
            obj = new ObjetoAposta(item2);
            objetosGanhadores.add(obj);
            
            IGerenciadorResultado gerenciadorResultado = new GerenciadorResultadoCavalos();
            gerenciadorResultado.obterResultado(objetosGanhadores, gerenciadorApostador.getDAOApostadores());
            
           if(gerenciadorResultado.getResultado() == null){
               textoGanhador.removeAll();
               textoGanhador.setText("Nenhum ganhador");
           }
           else{
              textoGanhador.removeAll();
              IRegraJogo regraJCavalos = new RegraJogoCavalos();
              regraJCavalos.calcularTabelaPremiacao(gerenciadorApostador.getDAOApostadores());  
              
              System.out.print(gerenciadorResultado.getResultado().getClassificacao().size());
                            
              textoGanhador.setText(">MANEIRA: VENCEDOR");
              String temp = String.valueOf(regraJCavalos.premioPorApostador(gerenciadorResultado.getResultado()).get(0).getPremio());
              for(int i = 0; i < gerenciadorResultado.getResultado().getClassificacao().size(); i++) //todos os ganhadores
              {
                  for(int j = 0; j < gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().size(); j++) //todas as apostas
                  {     
                        System.out.println(io.getObjetosAposta().get(id).getNome());
                        if(gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getManeira().equals("Vencedor") &&
                           gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getObjetosAposta().get(0).getNome().equals(io.getObjetosAposta().get(id).getNome()))
                        {  
                           textoGanhador.setText(textoGanhador.getText() + "\n Ganhador: \n " + gerenciadorResultado.getResultado().getClassificacao().get(i).getNome() + " --- " + temp);
                           break;
                        }                    
                  }
              }
              
              textoGanhador.setText(textoGanhador.getText() + "\n \n>MANEIRA: PLACER"); 
              temp = String.valueOf(regraJCavalos.premioPorApostador(gerenciadorResultado.getResultado()).get(1).getPremio());
              for(int i = 0; i < gerenciadorResultado.getResultado().getClassificacao().size(); i++) //todos os ganhadores
              {
                  for(int j = 0; j < gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().size(); j++) //todas as apostas
                  {                                                
                        if(gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getManeira().equals("Placer") &&
                           (gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getObjetosAposta().get(0).getNome().equals(io.getObjetosAposta().get(id).getNome()) ||
                           gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getObjetosAposta().get(0).getNome().equals(item2)))
                        {                             
                          
                           textoGanhador.setText(textoGanhador.getText() + "\n Ganhador: \n " + gerenciadorResultado.getResultado().getClassificacao().get(i).getNome() + " --- " + temp);
                           break;
                        }
                  }
              }
              
              textoGanhador.setText(textoGanhador.getText() + "\n \n>MANEIRA: DUPLA");
              temp = String.valueOf(regraJCavalos.premioPorApostador(gerenciadorResultado.getResultado()).get(2).getPremio());
              for(int i = 0; i < gerenciadorResultado.getResultado().getClassificacao().size(); i++) //todos os ganhadores
              {
                  for(int j = 0; j < gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().size(); j++) //todas as apostas
                  {                        
                        if(gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getManeira().equals("Dupla"))
                        {          
                            if(gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getObjetosAposta().get(0).getNome().equals(objetosGanhadores.get(0).getNome()) &&
                               gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getObjetosAposta().get(1).getNome().equals(objetosGanhadores.get(1).getNome()))
                            {
                                    textoGanhador.setText(textoGanhador.getText() + "\n Ganhador: \n " + gerenciadorResultado.getResultado().getClassificacao().get(i).getNome() + " --- " + temp);
                                    break;
                            }
                            else if(gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getObjetosAposta().get(0).getNome().equals(objetosGanhadores.get(1).getNome()) &&
                                    gerenciadorResultado.getResultado().getClassificacao().get(i).getDAOAposta().getApostas().get(j).getObjetosAposta().get(1).getNome().equals(objetosGanhadores.get(0).getNome()))
                            {
                                    textoGanhador.setText(textoGanhador.getText() + "\n Ganhador: \n " + gerenciadorResultado.getResultado().getClassificacao().get(i).getNome() + " --- " + temp);
                                    break;
                            }
                        }
                  }
                        
              }
           }
        }
        }
        catch (IndexOutOfBoundsException e) {
               System.out.println("Exception lançada: " + e.getMessage());
        }   
    }//GEN-LAST:event_cbObjetos2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaResultado().setVisible(true);
            }
        });
    }                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbObjetos;
    private javax.swing.JComboBox cbObjetos2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textoGanhador;
    // End of variables declaration//GEN-END:variables
}
